SUPPORTED_HS_CODE = "3902.10"
SUPPORTED_PRODUCT_NAME = "PP Resin"
SUPPORTED_DESTINATION_PORT = "MYPKG"
SUPPORTED_IMPORT_COUNTRY = "MY"
SUPPORTED_INCOTERM = "FOB"
SUPPORTED_COUNTRY_CODES = {"MY", "CN", "TH", "ID"}
SUPPORTED_ORIGIN_COUNTRIES = {"CN", "TH", "ID"}
SUPPORTED_PORT_CODES = {"MYPKG", "CNNGB", "CNSZX", "THBKK", "IDJKT"}
DEFAULT_FX_PAIR_TICKERS = {
    "USDMYR": "MYR=X",
    "CNYMYR": "CNYMYR=X",
    "THBMYR": "THBMYR=X",
    "IDRMYR": "IDRMYR=X",
}
DEFAULT_ENERGY_SERIES = {
    "BZ=F": "Brent Crude",
    "NG=F": "Natural Gas",
}
DEFAULT_HOLIDAY_COUNTRIES = ("MY", "CN", "TH", "ID")
DEFAULT_RESIN_SANE_PRICE_RANGE = (100.0, 5000.0)
DEFAULT_RESIN_SANE_PRICE_RANGE_BY_CURRENCY = {
    "USD": (100.0, 5000.0),
    "CNY": (1000.0, 30000.0),
    "MYR": (100.0, 25000.0),
}

